# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db415a9e6981065a9c031ffb857d4f6beef08c226ba9ae8f23eb1022f043bc12e10acaddcf826a1ba28d31acaa30049f46ae77000c24f233c3f122799c64b66

test:
  secret_key_base: 9c9ac902e63b2d8ba00f90898d91aafccca0da80709915ab0461d78ff699136fad0517552bfb139e969887c98f81d93c06b63083e9d2a58a65b6afb70ba1ffe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
